// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SMSAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SmsModel
    {
        /// <summary>
        /// Initializes a new instance of the SmsModel class.
        /// </summary>
        public SmsModel() { }

        /// <summary>
        /// Initializes a new instance of the SmsModel class.
        /// </summary>
        public SmsModel(string fromProperty = default(string), string to = default(string), string body = default(string))
        {
            FromProperty = fromProperty;
            To = to;
            Body = body;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public string FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public string To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

    }
}
